myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [

    path('admin/', admin.site.urls),
    path('',views.homepage),
    path('about/',views.about),
    path('posts/',include('posts.urls')),
    path('users/',include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('',views.posts_list,name="list"),
    path('new-post/',views.posts_new,name="new-post"),
    path('<slug:slug>',views.post_page,name="page"), 
]

myproject/users/urls.py
from django.urls import path
from . import views

app_name='users'

urlpatterns = [
    path('register/',views.new_user,name='register'),
    path('login/',views.login_view,name='login'), 
    path('logout/',views.logout_view,name='logout') 
]

myproject/posts/models.py
from django.db import models # type: ignore
import datetime
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title=models.CharField( max_length=50)
    body=models.TextField()
    slug=models.SlugField()
    date=models.DateTimeField(auto_now_add=True)
    banner=models.ImageField(default='fallback.png',blank=True)
    author=models.ForeignKey(User,on_delete=models.CASCADE,default=None)
 
    def __str__(self) -> str:
        return self.title

myproject/users/models.py
from django.db import models

# Create your models here.

myproject/posts/forms.py
# creating an new post forms to visible in the web
from django import forms
from . import models

# importing the models to this file to use the feilds in the model
class Createpost(forms.ModelForm):
    # create an nested class Meta the name cant be changed
    class Meta:
        model=models.Post
        fields=['title','body','slug','banner']

myproject/myproject/views.py
#from django.http import HttpResponse
from django.shortcuts import render
def homepage(request):
    #return HttpResponse('Hello !')
    return render(request, 'home.html')

def about(request):
    #return HttpResponse('My about page')
     return render(request, 'about.html')

myproject/posts/views.py
import wave
from django.shortcuts import redirect, render
from .models import Post
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def posts_list(request):
    posts=Post.objects.all().order_by('-date') 
    return render(request, 'posts/posts_list.html',{'posts':posts})

def post_page(request, slug):
    post=Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html',{'post':post})
@login_required(login_url="/users/login/")
def posts_new(request):
    # adding form to view 
    # adding 'FILES' request because we are adding immage
    if request.method=='POST':
        form=forms.Createpost(request.POST,request.FILES)
        if form.is_valid():
            #save with user
            newpost=form.save(commit=False)
            newpost.author=request.user
            newpost.save()
            return redirect('posts:list')
    else:    
      form=forms.Createpost()
    return render(request,'posts/post_new.html',{'form':form})#add form in the return funtion
     

myproject/users/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

def new_user(request):
    if request.method =="POST":
        form=UserCreationForm(request.POST)
        if form.is_valid():
            login(request,form.save())
            return redirect("posts:list")
    else:
        form=UserCreationForm()
    return render(request, "users/register.html",{"form":form})

def login_view(request):
    if request.method=="POST":
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            # errer in this if statement it is not going or redirecting to next vlaue
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("posts:list") 
    else:
        form=AuthenticationForm()
    return render(request, "users/login.html",{"form":form})

def logout_view(request):
    if request.method=="POST":
        logout(request)
        return redirect("posts:list")

myproject/posts/templates/posts/post_new.html
{% extends 'layout.html' %}

{% block title %}
  new post
{% endblock %}

{% block content %}
<section>
  <h1>New post</h1>
  {% comment %} from add image tag in the banner we are using the 'enctype' means encoding type
  action refers to posts app in which urls.py named new-post which direct to the post_new.html
  {% endcomment %}
  <form class="form-with-validation login-form" action="{% url 'posts:new-post' %}" method="post"
  enctype="multipart/form-data">
     {% csrf_token %}
     {{ form }}
     <button class="form-submit">Add post</button>
</form>  
</section>
{% endblock %}

 

myproject/posts/templates/posts/post_page.html
{% extends 'layout.html' %}

{% block title %}
{{post.title}}
{% endblock %}

{% block content %}
  <section>
  <h1>{{post.title}}</h1>
  <div class="image-container" >
    <img
     class="banner"
     src="{{post.banner.url}}" 
     alt="{{post.title}}"
    />
  </div> 
    <p>{{post.date}}</p>
    <p>{{post.body}}</p>
  </section>  
{% endblock %}

 

myproject/posts/templates/posts/posts_list.html
{% extends 'layout.html' %}

{% block title %}
  post
{% endblock %}

{% block content %}
  <section>
    <h1>Post</h1>
    {% for post in posts %}
      <article class='post'>
        <h2>
          <a href="{% url 'posts:page' slug=post.slug %}">
          {{post.title}} 
          </a>
        </h2>
        <p>{{post.date}} by {{post.author}}</p>
        <p>{{post.body}}</p>
      </article>
    {% endfor %}
  </section>

{% endblock %}

myproject/users/templates/users/login.html
{% extends 'layout.html' %}

{% block title %}
User Login
{% endblock %}

{% block content %}
<section class="login-section">
    <div class="login-container">
        <h1>User Login</h1>
        <form class="form-with-validation login-form" action="/users/login/" method="post" id="loginForm">
            {% csrf_token %}
            {{ form }}
            {% if request.GET.next %}
               <input type="hidden" name="next" value="{{request.GET.next}}" />
            {% endif %}
            <button class="form-submit" id="submitButton">
                Submit <span class="loading-spinner" style="display: none;"></span>
            </button>
            <p class="success-message" id="successMessage">Done!</p>
        </form>
        <p class="signup-prompt">Don't have an account? <a href="{% url 'users:register' %}">Sign up</a></p>
    </div>
</section>
{% endblock %}

myproject/users/templates/users/register.html
{% extends 'layout.html' %}

{% block title %}
Register New User
{% endblock %}

{% block content %}
<section class="register-section">
    <div class="register-container">
        <h1>Register a New User</h1>
        <form class="form-with-validation register-form" action="/users/register/" method="post" id="registerForm">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="form-submit" id="submitButton">
                Submit <span class="loading-spinner" style="display: none;"></span>
            </button>
            <p class="success-message" id="successMessage">Done!</p>
        </form>
    </div>
</section>
{% endblock %}